export const siteConfig = {
  canonicalUrl: 'https://tinaba.bancaprofilo.it',
  productionHostname: 'tinaba.bancaprofilo.it',
  destinations: {
    onboarding: 'https://onboarding.bancaprofilo.it',
    homeBanking: 'https://homebanking.tinaba.it/',
    business: 'https://business.tinaba.it/',
    businessDashboard: 'https://backoffice.tinaba.it/',
    investments: 'https://investiamo.bancaprofilo.it/',
    investmentsGuide: 'https://investiamo.tinaba.it/',
    ambassador: 'https://tinaba.bancaprofilo.it/form-ambassador/',
    promoScuola: 'https://promo.bancaprofilo.it/tinabascuola',
    promoScuolaForm: 'https://promo.bancaprofilo.it/tinabascuola/form',
    wishope: 'https://wishope.tinaba.it/',
    wishope2024: 'https://wishope-2024.tinaba.it/',
    wishope2023: 'https://wishope-2023.tinaba.it/',
    wishopeCri4Kids: 'https://crocerossamilano.wishope.tinaba.it/',
    alipayPlusCountries: 'https://www.alipayplus.com/mobile-payment-provider-list',
    americanExpress: 'https://www.americanexpress.com/it/',
    psd2: 'https://www.bancaprofilo.it/psd2/',
    whistleblowing: 'https://www.bancaprofilo.it/whistleblowing/',
    course: 'https://corsoicesdabocconi.tinaba.it/',
  },
  services: {
    cookiebotScript: 'https://consent.cookiebot.com/uc.js',
    googleTagManagerScript: 'https://www.googletagmanager.com/gtm.js',
  },
  social: {
    instagram: 'https://www.instagram.com/tinaba_app/',
    facebook: 'https://www.facebook.com/TinabaOfficial/',
    x: 'https://twitter.com/TinabaOfficial',
    youtube: 'https://www.youtube.com/channel/UCmOdkb7KUseVSHDTYCM3gCg',
    linkedin: 'https://www.linkedin.com/company/tinaba/',
  },
  appStores: {
    googlePlay: 'https://play.google.com/store/apps/details?id=it.tinaba.app',
    appStore: 'https://itunes.apple.com/it/app/id1063359568',
    appGallery: 'https://appgallery.huawei.com/#/app/C102692785',
  },
};
